{{- range .Values.ingresses }}
---
{{- $svcName := .ServiceName -}}
{{- $svcPort := .ServicePort -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .name }}
  labels:
    chart: {{ include "ingresses.chart" $ }}
    release: {{ $.Release.Name }}
  {{- with .annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  rules:
  {{- range .hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          - path: "/*"
            backend:        
              serviceName: ssl-redirect
              servicePort: use-annotation        
          - path: "/*"
            backend:
              serviceName: {{ $svcName }}
              servicePort: {{ $svcPort }}
  {{- end }}
{{- end }}