{{- range $name, $secret := .Values.secrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secret.name }}
  namespace: {{ $secret.namespace }}
data:
  {{- $sourceSecret := $name }}
  {{- if $secret.secretRef }}
    {{- $sourceSecret = $secret.secretRef }}
  {{- end }}

  {{- $sourceData := index $.Values.secrets $sourceSecret }}
  {{- if $sourceData.values }}
    {{- range $key, $val := $sourceData.values }}
  {{ $key }}: {{ $val | toString | b64enc }}
    {{- end }}
  {{- end }}
type: {{ $secret.type | default "Opaque" }}
{{- end }}
