{{- range .Values.secrets -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
  namespace: {{ .namespace }}
data:
{{- range $key, $val := .values }}
  {{$key}}: {{$val|b64enc}}
{{ end -}}
type: {{ .type | default "Opaque" }}
{{ end }}
