apiVersion: v2
appVersion: 1.5.0
dependencies:
- name: k8ssandra-common
  repository: file://../k8ssandra-common
  version: 0.28.0
description: A Helm chart for Kubernetes
name: cass-operator
type: application
version: 0.28.0
