apiVersion: rbac.authorization.k8s.io/v1

kind: ClusterRoleBinding
metadata:
  name: {{ include "fullname" . }}-binding
subjects:
- kind: Group
  name: {{ .Values.name }} # Name is case sensitive
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: {{ include "fullname" . }}
  apiGroup: rbac.authorization.k8s.io