{{- if .Values.medusa.enabled }}

apiVersion: v1
kind: Secret
metadata:
  name: cassandra-backups-secret
type: Opaque
stringData:
 medusa_s3_credentials: |-
    [default]
    aws_access_key_id = {{ .Values.secrets.awsaccesskeyid  }}
    aws_secret_access_key = {{ .Values.secrets.awssecretaccesskey  }}

{{- end }}