apiVersion: v1
appVersion: "21.10.0"
description: Report Kubernetes cluster and pod resource requests vs usage and generate static HTML
name: kube-resource-report
version: 0.3.2
home: https://github.com/hjacobs/kube-resource-report.git
