proxyinjector:
  replicas: 1
  mount: "configmap"

  tolerations: {}
  labels:
    provider: stakater
    group: com.stakater.platform
    version: 0.0.2
  image:
    name: moveax/proxyinjector
    tag: "latest"
    pullPolicy: IfNotPresent

  data:
    config: |-
      proxyconfig:
        gatekeeper-image: "moveax/keycloak-gatekeeper:latest"
        enable-default-deny: true
        secure-cookie: true
        verbose: true
        enable-logging: true
        cors-origins:
          - '*'
        cors-methods:
        - GET
        - POST
        resources:
        - uri: '/*'


  # Set to false if you want to only watch its own namespace
  watchGlobally: true
  configFilePath: /etc/ProxyInjector

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi

safeToEvict: false

podDisruptionBudget:
  # https://kubernetes.io/docs/tasks/run-application/configure-pdb/
  enabled: false
  minAvailable:
  maxUnavailable:

nodeSelector: {}