apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mongodb-express.fullname" . }}-secrets
  labels:
    {{- include "mongodb-express.labels" . | nindent 4 }}  
type: Opaque
data:
{{- range $key, $value := .Values.secrets }}
    {{ $key }}: {{ $value | b64enc }}
    {{- end }}
