apiVersion: v1
kind: Service
metadata:
  name: {{ include "mongodb-express.fullname" . }}
  labels:
    {{- include "mongodb-express.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8081
      name: http
  selector:
    {{- include "mongodb-express.selectorLabels" . | nindent 4 }}
