{{- if or (not .Values.externalSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgresql.fullname" . }}
type: Opaque
data:
   POSTGRES_PASSWORD: {{ .Values.secrets.postgresPassword | b64enc }}
   POSTGRES_USER: {{ .Values.secrets.postgresUser | b64enc }}
{{- end -}}