{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: {{ template "ovh-lb-controller.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
  name: {{ template "ovh-lb-controller.fullname" . }}
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["services", "service", "services/status"]
  verbs: ["get", "watch", "list", "patch", "update", "create", "delete" ]
- apiGroups: [""]
  resources: ["events", "event"]
  verbs: [ "create", "patch", "watch", "update" ]
{{- end -}}
