apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ovh-lb-controller.fullname" . }}
  labels:
    {{- include "ovh-lb-controller.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "ovh-lb-controller.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "ovh-lb-controller.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ if .Values.rbac.create }}{{ template "ovh-lb-controller.fullname" . }}{{ else }}"{{ .Values.rbac.serviceAccountName }}"{{ end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}

      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/usr/local/bin/kopf"]
          args:
          - run
          - -m
          - ovh_lb_controller.operator
          - --liveness=http://0.0.0.0:8080/healthz
{{- with .Values.image.args }}
{{ toYaml . | indent 10 }}
{{- end }}      
          envFrom:
          - secretRef:
              name: {{ include "ovh-lb-controller.fullname" . }}-secret

          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
          resources:
            {{- toYaml .Values.resources | nindent 12 }}

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}