---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ovh-lb-controller.fullname" . }}-secret
  namespace: {{ .Release.namespace }}
data:
{{- range $key, $value := .Values.secrets }}
    {{ $key }}: {{ $value | b64enc | quote }}
    {{- end }}