apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
{{ include "proxyinjector-labels.stakater" . | indent 4 }}
{{ include "proxyinjector-labels.chart" . | indent 4 }}
  name: {{ template "proxyinjector-name" . }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.proxyinjector.replicas }}
  revisionHistoryLimit: 2
  selector:
    matchLabels:
{{ include "proxyinjector-labels.selector" . | indent 6 }}
  template:
    metadata:
      labels:
{{ include "proxyinjector-labels.selector" . | indent 8 }}
      annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: {{ .Values.safeToEvict | quote }}
    spec:
      {{- if .Values.proxyinjector.tolerations }}
      tolerations:
{{ toYaml .Values.proxyinjector.tolerations | indent 8 -}}
      {{- end }}
      containers:
      - env:
        - name: CONFIG_FILE_PATH
          value: "{{ .Values.proxyinjector.configFilePath }}/config.yml"
      {{- if eq .Values.proxyinjector.watchGlobally false }}
        - name: KUBERNETES_NAMESPACE
          value: "{{ .Values.watchedNamespace }}"
      {{- end }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
        image: "{{ .Values.proxyinjector.image.name }}:{{ .Values.proxyinjector.image.tag }}"
        imagePullPolicy: {{ .Values.proxyinjector.image.pullPolicy }}
        name: {{ template "proxyinjector-name" . }}
        volumeMounts:
          - mountPath: {{ .Values.proxyinjector.configFilePath }}
            name: config-volume
      serviceAccountName: {{ template "proxyinjector-name" . }}
      volumes:
        - name: config-volume
        {{- if eq .Values.proxyinjector.mount "secret" }}
          secret:
            secretName: {{ template "proxyinjector-vol-config-name" . }}
        {{- else }}
          configMap:
            name: {{ template "proxyinjector-name" . }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}        