---
# Source: aws-storage-class/templates/storageclass-gp2.yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gp2
  annotations:
    storageclass.beta.kubernetes.io/is-default-class: "true"
  labels:
    kubernetes.io/cluster-service: "true"
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
  encrypted: "true"
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
---
# Source: aws-storage-class/templates/storageclass-io1-10.yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: io1-10
  annotations:
    storageclass.beta.kubernetes.io/is-default-class: "false"
  labels:
    kubernetes.io/cluster-service: "true"
provisioner: kubernetes.io/aws-ebs
parameters:
  type: io1
  iopsPerGB: "10"
  encrypted: "true"
volumeBindingMode: WaitForFirstConsumer
---
# Source: aws-storage-class/templates/storageclass-io1-20.yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: io1-20
  annotations:
    storageclass.beta.kubernetes.io/is-default-class: "false"
  labels:
    kubernetes.io/cluster-service: "true"
provisioner: kubernetes.io/aws-ebs
parameters:
  type: io1
  iopsPerGB: "20"
  encrypted: "true"
volumeBindingMode: WaitForFirstConsumer
