apiVersion: v1
kind: Service
metadata:
  name: http-{{ include "pgadmin.fullname" . }}
  labels:
    {{- include "pgadmin.labels" . | nindent 4 }}
  {{- if .Values.service.annotations }}
  annotations:
    {{- .Values.service.annotations | toYaml | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: {{ .Values.service.portName }}
  selector:
    app.kubernetes.io/name: {{ include "pgadmin.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
