apiVersion: rbac.authorization.k8s.io/v1

kind: ClusterRoleBinding
metadata:
  name: readonly-role-binding
subjects:
- kind: Group
  name: readonly # Name is case sensitive
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: readonly-cluster-role
  apiGroup: rbac.authorization.k8s.io