{{- if .Values.gp2.enabled }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gp2
  annotations:
    storageclass.beta.kubernetes.io/is-default-class: {{ .Values.gp2.default | quote }}
  labels:
    kubernetes.io/cluster-service: "true"
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
  encrypted: "true"
allowVolumeExpansion: {{ .Values.gp2.allowVolumeExpansion }}
volumeBindingMode: {{ .Values.gp2.volumeBindingMode }}
{{- end }}