# Default values for ovh-lb-controller.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: moveax/ovh-lb-controller
  tag: 0.1
  pullPolicy: IfNotPresent

  args: 
   - --verbose
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

secrets:
  OVH_ENDPOINT : secret
  OVH_APPLICATION_KEY : secret
  OVH_APPLICATION_SECRET : secret
  OVH_CONSUMER_KEY : secret
  OVH_SERVICE_NAME : secret
  REGION_NAME : secret
  OS_CLOUD_NAME : secret
# OpenStack
  OS_PROJECT_NAME: secret
  OS_PROJECT_ID: secret
  OS_USERNAME: secret
  OS_PASSWORD : secret
  OS_AUTH_URL: secret
  OS_USER_DOMAIN_NAME: secret
  OS_PROJECT_DOMAIN_NAME: secret
  OS_TENANT_ID: secret
  OS_TENANT_NAME: secret


serviceAccount:
  create: true
rbac:
  create: true 
podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000


resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
